### ISSUE TITLE
Some questions about the Z mat.

### ISSUE THREAD

**Issue by sean-001** [gmntu/mobilehand#20]
Hi, very great work !

I feel some puzzles about the generation of Z mat.

```python
# Convert rotation vector (3 by 1 or 1 by 3) to rotation matrix (3 by 3)
rvec2rmat = lambda rvec : cv2.Rodrigues(rvec)[0]
# Note: j1 is the joint of interest and j2 is its parent (1 by 3)
rotate_finger = lambda j1, j2 : rvec2rmat(np.array([0, np.arctan((j1[2]-j2[2])/(j1[0]-j2[0])),0])) # Rotate about y axis

Z[0:2,0:3] = rotate_finger(Jrest[1,:],Jrest[0,:])[1:3,:] # 0:MCP abduct/adduct, 1:MCP flex/ext
```

If I understand correctly, the return of function rotate_finger is a rotation matrix, so why Z[0:2,0:3] = rotate_finger(...)[1:3,:] ?
(bs, 23) dot (23, 45) = (bs, 45) and the pose of mano input should be 45 axis-angle values, I just can not understand why the Z mat can be generated by the rotation matrix such as Z[0:2,0:3] = rotate_finger(...)[1:3,:], are the results of (bs, 23) dot (23, 45) 45 axis-angle values？.

**Comment by gmntu** [comment]
Hi @sean-001 yes you understand correctly that the return of `rotate_finger` is a 3 by 3 rotation matrix.

Then we refer to the [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188), and note that the new 
- x-axis controls joint axial rotation
- y-axis controls joint abduct/adduct
- z-axis controls joint flexion/extension

Since we only want y-axis abduct/adduct and z-axis flexion/extension for finger MCP joints, they only require the second (index 1) and third component (index 2) of the rotation matrix from `rotate_finger(...)[1:3,:]`
Similarly, we only want z-axis flexion/extension for finger PIP/DIP joints, they only require the third component (index 2) of the rotation matrix from `rotate_finger(...)[2,:]`

**Comment by sean-001** [comment]
> Hi @sean-001 yes you understand correctly that the return of `rotate_finger` is a 3 by 3 rotation matrix.
> 
> Then we refer to the [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188), and note that the new
> 
> * x-axis controls joint axial rotation
> * y-axis controls joint abduct/adduct
> * z-axis controls joint flexion/extension
> 
> Since we only want y-axis abduct/adduct and z-axis flexion/extension for finger MCP joints, they only require the second (index 1) and third component (index 2) of the rotation matrix from `rotate_finger(...)[1:3,:]` Similarly, we only want z-axis flexion/extension for finger PIP/DIP joints, they only require the third component (index 2) of the rotation matrix from `rotate_finger(...)[2,:]`

Thanks for your reply, it helps me a lot !
